### PR TITLE
Update to node 14, and as many dependencies as possible

### PR DESCRIPTION
**Pull request by jacoblb64**
#### Major changes
- Update to latest node LTS, 14.x
- Update to Typescript 4.x
- Removed `package-lock.json` -- NPM is now blocked, using yarn is now enforced!

#### Medium changes
- Update most major deps
- Some code changes for breaking changes
- Rework to new husky / lint-staged / prettier flow

#### Minor changes
- Update all minor/patch deps
- Some formatting changes were triggered
- Some other bugfixes are baked in here

#### Not in scope
- excluded react 16 -> 17 and related changes for now
- history and react-router-dom updates
- excluding updating ts-jest and testing functions -- @bvillaroman need to chat about this

### CODE REVIEW

**Review by kaiserfenix — APPROVED** [review]

**Review by stanzheng — APPROVED** [review]
LGTM, build on windows shell with node 14.16.1

**Comment by jacoblb64** [comment]
[Bring front-end dependencies up to date](https://trello.com/c/DfkMP3eO/846-bring-front-end-dependencies-up-to-date)

**Comment by jacoblb64** [comment]
@stanzheng finally found the react-router issue, turns out history@5.x, which is incompatible with react-router-dom@5.x :-/

> Documentation for version 5 can be found in the docs directory. This is the current stable release. Version 5 is used in React Router version 6.

> Documentation for version 4 can be found on the v4 branch. Version 4 is used in React Router versions 4 and 5.

Anyway, fixed it, so please take a look if you have sometime and hopefully we can get this in soon!

**Review by stanzheng — APPROVED** [review]

**Comment by stanzheng** [comment]
LGTM, built on OSX node 14. 

note: we are using libsas 4 which does not have support for node16 so we are locked on node14 for a bit

https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove

**Pull request merged**
