### PR TITLE
Make mega GAM campaigns more mobile-friendly

### PR DESCRIPTION
**Pull request by chrisng93**
Make mega GAM campaigns more mobile-friendly

Screen Shot 2020-12-01 at 7 13 59 PM

### CODE REVIEW

**Comment by chrisng93** [comment]
@nanxiy i ended up doing the collapsed version for mobile since the full version w/ the merchant store images didn't look that great on a smaller screen

**Comment by nanxiy** [comment]
> @nanxiy i ended up doing the collapsed version for mobile since the full version w/ the merchant store images didn't look that great on a smaller screen

oh nice! my only concern is that the card expands when the name is longer. I had accounted for our longest merchant name in my mocks to keep it on two lines - does it not translate well when you code it?

**Review by justintmckibben — APPROVED** [review]

**Comment by chrisng93** [comment]
@nanxiy oh i think i missed the font-size change for mobile. here's what it looks like now (i had to un-bold the names otherwise they'd be too long):
image

**Comment by chrisng93** [comment]
@nanxiy i merged this pr to unblock another thing, but let me know if this looks good to you. if not, i can make edits

**Pull request merged**
