### PR TITLE
Added copy to clipboard button

### PR DESCRIPTION
**Pull request by danthaman44**
Screen Shot 2020-05-21 at 11 28 29 PM

### CODE REVIEW

**Comment by jtmckibb** [comment]
Nit but the graphic doesn't look centered in the button. Maybe there is some whitespace on the left of the graphic that needs to be trimmed? @nanxiy do you mind helping with the trimming?

**Comment by nanxiy** [comment]
I have new icons for the social share icons on figma if you want to grab those!

**Comment by jtmckibb** [comment]
Actually let's leave it as is then since this is going to be replaced next week with the new social share tab

**Comment by danthaman44** [comment]
ahh yeah the SVG was larger than the button itself so I had add some padding to shrink + center it...this was the best I could do with my mediocre CSS skills 😅

**Pull request merged**
