### PR TITLE
adding total merchants

### PR DESCRIPTION
**Pull request by ath-chen**
### [Description of changes]
Adding total merchant count to merchant dashboard

### CODE REVIEW

**Review by kaiserfenix — COMMENTED** [review]
mind including a screenshot of your change? I'll approve after!

**Review by jacoblb64 — APPROVED** [review]
Would love to see a screenshot in action, but other than that looks great!

**Comment by aliceluo2048** [comment]
Are we including closed merchants?

**Comment by ath-chen** [comment]
@jacoblb64 i've been avoiding setting up my local env lol, but it's finally set up. here's the screenshot you were looking for! 

Screen Shot 2021-04-23 at 6 21 05 PM

**Comment by jacoblb64** [comment]
@ath-chen looks great! Thanks for taking the time :) Let's get this merged then!

**Review by jacoblb64 — APPROVED** [review]
Looks good!

**Pull request merged**
